60 Realisation/MayChamCong/NtbSoft.ERP.Web/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace NtbSoft.ERP.Web.Controllers
{
    [Authorize]
    public class ManagerController : Controller
    {
        public ActionResult Home()
        {
            //ViewBag.Title = "Standard Operation Analysis";
            ViewBag.Title = "Máy chấm công";

            //TestTest();
            return View();
        }

        private void TestTest()
        {
            NtbSoft.ERP.Models.clsSysTest _test
                = new Models.clsSysTest();

            Entity.clsSysTestInfo Item = new Entity.clsSysTestInfo();
            Item.Id = 2;
            Item.CardId = "3";
            Item.Name = "Hai";
            Item.Value = 100;
            _test.Insert(Item);
        }

    }
}

60 Realisation/MayChamCong/NtbSoft.ERP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/cssui")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background: #00B1FF;border:none;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Máy Chấm Công", "Home", "Manager", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Đăng nhập", "Home", "Manager", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Công Ty TNHH Phát Triển Công Nghệ Nam Thanh Bình</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

60 Realisation/MayChamCong/NtbSoft.ERP.Web/Views/Shared/_LayoutDIC.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <link href="../EasyUI/easyui.css" rel="stylesheet" type="text/css" />
    <link href="../EasyUI/icon.css" rel="stylesheet" type="text/css" />
    <script src="../EasyUI/jquery-1.11.3.js" type="text/javascript"></script>
    <script src="../EasyUI/jquery.easyui.min.js" type="text/javascript"></script>
    
    
    <script src="~/Scripts/jquery-formats.js"></script>
    <script src="~/EasyUI/datagrid-cellediting.js"></script>
    <script src="~/Scripts/jquery.extends.js"></script>
    <style type="text/css">
        .easyui-layout {
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            overflow: hidden;
            height: 100%;
        }

        .menu-ctrl {
            background: #d5fdef; /*** 007FCF ***/ /**thanh trên cái danh sách*/
        }

            .menu-ctrl a {
                width: 7%;
            }

            .menu-ctrl .action {
                color: #0E2D83;
            }

                .menu-ctrl .action:hover {
                    color: black;
                }

        .format-text {
            color: #0E2D5F;
        }

        .center-header {
            font-weight: bold;
        }

        .datagrid-header td.datagrid-header-over,
        div.datagrid-header td {
            background: #74ADB3; /*thanh ngang màu xanh*/
            color: #ffffff;
        }

        .datagrid-cell-rownumber {
            height: 24px;
            background: #74ADB3; /*thanh dọc danh sách*/
            color: #ffffff;
        }

        .datagrid-row {
            color: #0E2D5F; /*chữ trong danh sách*/
        }

        .datagrid-row-selected td {
            /**Mau mac dinh=> background: #FBEC88;***/
            background: #FBEC88;
            color: #2D3E50;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $(window).bind('keydown', function (event) {
                if (event.ctrlKey || event.metaKey) {
                    switch (String.fromCharCode(event.which).toLowerCase()) {
                        case 's':
                            event.preventDefault();
                            //alert('ctrl-s');
                            break;
                        case 'f':
                            event.preventDefault();
                            //alert('ctrl-f');
                            break;
                        case 'g':
                            event.preventDefault();
                            //alert('ctrl-g');
                            break;
                    }
                }
            });


        });

        function formatThousands(value, row, index) {
            if (value == null || value == "") return "";

            return '' + value.toLocaleString() + '';
        }


    </script>
</head>
<body class="easyui-layout" data-options="fit:true" oncontextmenu="return false;" >

    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>

60 Realisation/MayChamCong/NtbSoft.ERP.Web/Views/Shared/_LayoutGTD.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <link href="../EasyUI/easyui.css" rel="stylesheet" type="text/css" />
    <link href="../EasyUI/icon.css" rel="stylesheet" type="text/css" />
    <script src="../EasyUI/jquery-1.11.3.js" type="text/javascript"></script>
    <script src="../EasyUI/jquery-1.5.2.js" type="text/javascript"></script>
    <script src="~/EasyUI/datagrid-cellediting.js"></script>
    <script src="~/Scripts/jquery.extends.js"></script>

    <style type="text/css">
        .easyui-layout { top: 0;left: 0;bottom: 0;right: 0;overflow: hidden;}

        .menu-ctrl {background: #00B1FF;}
        .menu-ctrl a.action {color: #fff;}
        .menu-ctrl a.action:hover {color: black;}
        .format-text {color: #0E2D5F;}
        /*input[type=text] {
            text-transform: uppercase;
        }
        .textbox .textbox-text {
            text-transform: uppercase;
        }*/
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $(window).bind('keydown', function (event) {
                if (event.ctrlKey || event.metaKey) {
                    switch (String.fromCharCode(event.which).toLowerCase()) {
                        case 's':
                            event.preventDefault();
                            //alert('ctrl-s');
                            break;
                        case 'f':
                            event.preventDefault();
                            //alert('ctrl-f');
                            break;
                        case 'g':
                            event.preventDefault();
                            //alert('ctrl-g');
                            break;
                    }
                }
            });
        });
    </script>
</head>
<body class="easyui-layout" data-options="fit:true" oncontextmenu="return false;" onselectstart="return false">

    @RenderBody()

    @*@RenderSection("scripts", required: false)*@
</body>
</html>

60 Realisation/MayChamCong/NtbSoft.ERP.Web/Views/Shared/_LayoutMCC.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <link href="../EasyUI/easyui.css" rel="stylesheet" type="text/css" />
    <link href="../EasyUI/icon.css" rel="stylesheet" type="text/css" />
    <script src="../EasyUI/jquery-1.11.3.js" type="text/javascript"></script>
    <script src="../EasyUI/jquery.easyui.min.js" type="text/javascript"></script>

    <script src="~/Scripts/jquery-formats.js"></script>
    <script src="~/EasyUI/datagrid-cellediting.js"></script>
    <script src="~/Scripts/serializeObjects.js"></script>
    <script src="~/Scripts/jquery.extends.js"></script>
   
    <style type="text/css">
        .easyui-layout {
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            overflow: hidden;
            height: 100%;
        }

        .toolbar {
            background: #E0ECFF; /*** 007FCF ***/
        }
        .toolbar a{width:68px;}

        .menu-ctrl {
            background: #E0ECFF; /*** 007FCF ***/
        }
        .menu-ctrl a {width: 68px;}

        .menu-ctrl .action {color: #0E2D83;}
        .menu-ctrl .action:hover {color: black;}
        .format-text {color: #0E2D5F;}
        .center-header {font-weight: bold;}

        .datagrid-header td.datagrid-header-over,
                div.datagrid-header td {background: #006699;color: #fff;}
                .datagrid-cell-rownumber {height: 24px;background: #006699;color: #fff;}
                .datagrid-row {color: #0E2D80;}
                .datagrid-row-selected td {
                    /**Mau mac dinh=> background: #FBEC88;***/
                    background: #FBEC88;
                    color: #2D3E50;
                }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $(window).bind('keydown', function (event) {
                if (event.ctrlKey || event.metaKey) {
                    switch (String.fromCharCode(event.which).toLowerCase()) {
                        case 's':
                            event.preventDefault();
                            //alert('ctrl-s');
                            break;
                        case 'f':
                            event.preventDefault();
                            //alert('ctrl-f');
                            break;
                        case 'g':
                            event.preventDefault();
                            //alert('ctrl-g');
                            break;
                    }
                }
            });


        });
        

        function formatThousands(value, row, index) {
            if (value == null || value == "") return "";

            return '' + value.toLocaleString() + '';
        }
        function showMsg(title, msg) {
            $.messager.show({
                title: title, msg: msg, modal: true, timeout: 4000, showType: 'show',
                style: { left: '17%', top: '12%' }
            });
        }

        //function XacNhan(title, msg) {
        //    $.messager.confirm(title, msg, function (r) {
        //        if (r) { //Begin (r) =====================================
        //            return true;
        //        }//End (r)==============================================
        //    });
        //    return false;
        //}
    </script>
</head>
<body class="easyui-layout" data-options="fit:true" oncontextmenu="return false;" onselectstart="return false">

    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>

60 Realisation/MayChamCong/NtbSoft.ERP.Web/Views/Shared/_LayoutView.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <link href="../EasyUI/easyui.css" rel="stylesheet" type="text/css" />
    <link href="../EasyUI/icon.css" rel="stylesheet" type="text/css" />
    <script src="../EasyUI/jquery-1.11.3.js" type="text/javascript"></script>
    <script src="../EasyUI/jquery.easyui.min.js" type="text/javascript"></script>
    
    <script src="~/Scripts/jquery-formats.js"></script>
    <script src="~/EasyUI/datagrid-cellediting.js"></script>
    <script src="~/Scripts/jquery.extends.js"></script>

    <style type="text/css">
        .easyui-layout {
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            overflow: hidden;
            height:100%;
        }

        .menu-ctrl {
            background: #E0ECFF; /*** 007FCF ***/
        }
        .menu-ctrl a{width:7%}
        .menu-ctrl .action {color: #0E2D83;}
        .menu-ctrl .action:hover {color: black;}
        .format-text {color: #0E2D5F;}
        .center-header{font-weight:bold;}

        .datagrid-header td.datagrid-header-over,
        div.datagrid-header td {
            background: #006699;
            color: #fff;
        }

        .datagrid-cell-rownumber {
            height: 24px;
            background: #006699;
            color: #fff;
        }

        .datagrid-row {
            color: #0E2D80;
        }

        .datagrid-row-selected td {
            /**Mau mac dinh=> background: #FBEC88;***/
            background: #FBEC88;
            color: #2D3E50;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $(window).bind('keydown', function (event) {
                if (event.ctrlKey || event.metaKey) {
                    switch (String.fromCharCode(event.which).toLowerCase()) {
                        case 's':
                            event.preventDefault();
                            //alert('ctrl-s');
                            break;
                        case 'f':
                            event.preventDefault();
                            //alert('ctrl-f');
                            break;
                        case 'g':
                            event.preventDefault();
                            //alert('ctrl-g');
                            break;
                    }
                }
            });


        });

        function formatThousands(value, row, index) {
            if (value == null || value == "") return "";

            return '' + value.toLocaleString() + '';
        }

       
    </script>
</head>
<body class="easyui-layout" data-options="fit:true" oncontextmenu="return false;" onselectstart="return false">

    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>